"""Execute production pure projections/coroutine with synthetic dependencies only.

Pure quota projections use canonical synthetic group names. The manual response
is generated by the production module with synthetic preparation and Google IO;
no application lifespan, storage adapter or network client is started.
"""
import ast
import importlib.util
import os
import asyncio
import copy
import json
import math
from pathlib import Path
import sys
import types

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))
os.environ["ANTIGRAVITY_PANEL_TIMING_SAMPLE_RATE"] = "0"
for key in ("ANTIGRAVITY_PANEL_CHAIN_TIMEOUT_SECONDS", "ANTIGRAVITY_LEGACY_BATCH_WORK_TIMEOUT_SECONDS", "ANTIGRAVITY_SHUTDOWN_GRACE_SECONDS"):
    os.environ.pop(key, None)
policy = ast.parse((ROOT / 'src/antigravity_quota.py').read_text(encoding='utf-8'))
names = {'InvalidQuotaState', 'finite_quota_deadline', 'decode_quota_fields', 'quota_summary', 'public_state'}
ns = dict(copy=copy, json=json, math=math, GROUPS=('claude-gpt-shared', 'gemini-shared'), group_for=lambda model: model)
exec(compile(ast.Module(body=[n for n in policy.body if isinstance(n, (ast.ClassDef, ast.FunctionDef)) and n.name in names], type_ignores=[]), '<production quota projections>', 'exec'), ns)
future = 4070908800

def snapshot(state, timer=False):
    return ns['public_state']({'quota_group_states': {'gemini-shared': {'state': state, 'revision': 1}},
        'model_cooldowns': {'gemini-shared': future} if timer else {}, 'quota_credential_generation': 'synthetic'})

families = {'claude-opus-5-5': {'state': 'unavailable', 'reason': 'directory_query_failed'}}
class Backend:
    model_access_storage_ready = True
    async def model_access_observe_with_projection(self, *args, **kwargs):
        return {"applied": True, "public": {}, "families": families}
    async def manual_sync_quota(self, *args, **kwargs): raise AssertionError('failure must not sync quota')
async def prepare(filename, events, **kwargs):
    return types.SimpleNamespace(_backend=Backend()), {}, {'access_token': 'synthetic'}
async def fetch(*args, **kwargs):
    return {'success': False, 'upstream_status': 403, 'error': 'synthetic denied', 'response_source': 'google'}
pkg = types.ModuleType('synthetic_panel'); pkg.__path__ = []
p = types.ModuleType('synthetic_panel.creds'); p.fetch_quota_info = fetch; pkg.creds = p
sys.modules['synthetic_panel'] = pkg; sys.modules['synthetic_panel.creds'] = p
spec = importlib.util.spec_from_file_location('synthetic_panel.antigravity_manual', ROOT / 'src/panel/antigravity_manual.py')
manual = importlib.util.module_from_spec(spec)
spec.loader.exec_module(manual)
manual.prepare = prepare
print(json.dumps({
    'blocked': snapshot('blocked_unknown'), 'combined': snapshot('blocked_unknown', True),
    'override': snapshot('manual_override', True),
    'cached': {**ns['quota_summary']({'gemini-shared': future}, {'claude-gpt-shared': {'state': 'blocked_unknown', 'revision': 1}}, 100), 'model_access_families': families},
    'invalid': ns['quota_summary']({}, 'corrupt', 100),
    'failed': asyncio.run(manual.quota('synthetic.json', sync=True)),
}))
